Traceback (most recent call last):
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\stanbaek\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\stanbaek\git\books\.venv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class Cat:

    Cat.species = "Felis catus"   # class variable. 
    
    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hungry = True
        self.tired = True

    # instance method
    def description(self):
        __name_age__ = "{} is {} years old. ".format(self.name, self.age)
        
        if self.tired == True:
            __is_tired__ = "{} is tired. ".format(self.name)
        else:
            __is_tired__ = "{} is not tired. ".format(self.name)
        
        if self.hungry == True:
             __is_hungry__ = "{} is hungry. ".format(self.name)
        else:
            __is_hungry__ = "{} is not hungry. ".format(self.name)
        
        return str(__name_age__+__is_tired__+__is_hungry__)

    # instance method
    def meow(self):
        return "{} says {}".format(self.name, "Meow! Meow!")
    
    def feed(self):
        self.hungry = False
        print(self.meow())
        
    def sleep(self):
        self.tired = False
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[16], line 1[0m
[1;32m----> 1[0m [38;5;28;01mclass[39;00m [38;5;21;01mCat[39;00m:
[0;32m      3[0m     Cat[38;5;241m.[39mspecies [38;5;241m=[39m [38;5;124m"[39m[38;5;124mFelis catus[39m[38;5;124m"[39m   [38;5;66;03m# class variable. [39;00m
[0;32m      5[0m     [38;5;66;03m# Initializer / Instance Attributes[39;00m

Cell [1;32mIn[16], line 3[0m, in [0;36mCat[1;34m()[0m
[0;32m      1[0m [38;5;28;01mclass[39;00m [38;5;21;01mCat[39;00m:
[1;32m----> 3[0m     [43mCat[49m[38;5;241m.[39mspecies [38;5;241m=[39m [38;5;124m"[39m[38;5;124mFelis catus[39m[38;5;124m"[39m   [38;5;66;03m# class variable. [39;00m
[0;32m      5[0m     [38;5;66;03m# Initializer / Instance Attributes[39;00m
[0;32m      6[0m     [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, name, age):

[1;31mNameError[0m: name 'Cat' is not defined
NameError: name 'Cat' is not defined

